spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dolapcodecase
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.yaml
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: dolapcodecase
        dialect: org.hibernate.dialect.MySQL5Dialect


logging:
  level:
    org: info
    springframework: debug
